# Generated by Django 4.1.3 on 2022-11-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='is_status',
            field=models.BooleanField(choices=[(False, 'Pending'), (True, 'Completed')], default=False, verbose_name='Status?'),
        ),
    ]
