# Generated by Django 4.1.3 on 2022-11-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todoitem_options_alter_todoitem_is_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='is_status',
            field=models.BooleanField(choices=[(False, 'Pending'), (True, 'Completed')], default=False, verbose_name='Status?'),
        ),
    ]
